FROM nvcr.io/nvidia/cuda:12.1.0-cudnn8-devel-ubuntu22.04

# install app dependencies
RUN apt -y update && apt -y upgrade && apt-get -y install python3 git-lfs unzip psmisc wget git pip bc nano
RUN git lfs install
RUN pip install --upgrade pip


#COPY requirements.txt /tmp/requirements.txt
#RUN pip install --no-cache-dir --requirement /requirements.txt

RUN pip install --no-cache-dir --root-user-action=ignore -U  tqdm jsonlines 

RUN pip install --no-cache-dir --root-user-action=ignore -U numpy torch transformers vllm autoawq

RUN pip install flashinfer -i https://flashinfer.ai/whl/cu121/torch2.4

